Big update

diff --git a/recipes/bash b/recipes/bash
--- a/recipes/bash
+++ b/recipes/bash
@@ -1,44 +1,61 @@
+#! /bin/sh
+
 name=bash
-version=5.2.26
-revision=1
-tarball_url="https://ftp.gnu.org/gnu/bash/bash-5.2.21.tar.gz"
-tarball_blake2b="6789c9a0d9eb1ad167d4199bf1438d77934a7bbeae9f9fdd7167cae006b17b3894852440248db1bb6e9cf6d930e8a18b6448a3bb4db8831b2e6d1445b56a2065"
-source_allow_network=yes
-source_imagedeps="curl"
-source_hostdeps="autoconf automake libtool pkg-config"
-imagedeps="gcc"
-hostdeps="gcc autoconf automake libtool pkg-config"
+_version=5.3
+_patch=3
+version=${_version}.${_patch}
+revision=3
+tarball_url="https://ftpmirror.gnu.org/gnu/bash/bash-${_version}.tar.gz"
+tarball_blake2b="82d1b54322bbd1e8c2a93380f1b2888a42a1d7186e504f41cee705a0fdd41463d8f20baa1755051e1396192f8ebd089524767d933a9e0b5fb76f2588601539bb"
+imagedeps="build-essential"
+hostdeps="gcc pkg-config"
 deps="core-libs ncurses readline"
 
-regenerate() {
-    curl -Lo bash52-022 https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-022
-    curl -Lo bash52-023 https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-023
-    curl -Lo bash52-024 https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-024
-    curl -Lo bash52-025 https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-025
-    curl -Lo bash52-026 https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-026
+_get_patch() {
+    TMP_PATCH=$(mktemp)
+    curl -Lo "${TMP_PATCH}" https://ftpmirror.gnu.org/gnu/bash/bash-${_version}-patches/bash$(echo "${_version}" | sed 's/\.//g')-$1
+    if ! b2sum "${TMP_PATCH}" | grep -q $2; then
+        die "b2sum checksum fail for bash patch $1
+        expected $2
+        got      $(b2sum "${TMP_PATCH}")"
+    fi
+    patch -p0 <"${TMP_PATCH}"
+}
 
-    for f in bash52-02*; do
-        patch -p0 < $f
-    done
+early_prepare() {
+    _get_patch 001 ca275ade6a7132d316a4d1ffd401c9bfc6de691c58531385d85087c4d50723aeacb5b4bc7abef0165b4fb3cbed146a0fefd9dae4c99c1547f61618798a772d29
+    _get_patch 002 fec52c475b8126774290eab7a514f8145ae51edab150d413c09f5540719c9578fe1cb99987b6190a9cd82bd947e059c32e740a03d26e9d472af51356cafd8a32
+    _get_patch 003 6bb6f6679726d65f95c11b4ac1fb0729eaebfeef02de06e9fda4e3ac2bb3d328cc6f7fd6e29976a0907390ed6709cd5a0a6046682acbed73eb0470143bf144e1
+}
 
-        AUTOHEADER=true \
+prepare() {
     autotools_recursive_regen
 }
 
-build() {
+configure() {
+        bash_cv_func_sigsetjmp=missing \
     autotools_configure \
+        CFLAGS="$TARGET_CFLAGS \
+            -DDEFAULT_PATH_VALUE='\"/usr/local/sbin:/usr/local/bin:/usr/bin\"' \
+            -DSTANDARD_UTILS_PATH='\"/usr/bin\"' \
+            -DSYS_BASHRC='\"/etc/bash.bashrc\"' \
+            -DSYS_BASH_LOGOUT='\"/etc/bash.bash_logout\"' \
+            -DNON_INTERACTIVE_LOGIN_SHELLS \
+        " \
         --with-curses \
         --enable-readline \
         --without-bash-malloc \
-        --with-installed-readline="${sysroot}/usr/lib" \
-        CFLAGS="-g3 -O0"
+        --with-installed-readline="${sysroot}${prefix}/lib"
+}
 
+build() {
     make -j${parallelism}
 }
 
 package() {
     make install DESTDIR="${dest_dir}"
     ln -s bash "${dest_dir}${prefix}"/bin/sh
+    ln -s bash "${dest_dir}${prefix}"/bin/rbash
 
-    # post_package_strip
+    post_package_strip
 }
