Big update

diff --git a/recipes/readline b/recipes/readline
--- a/recipes/readline
+++ b/recipes/readline
@@ -1,48 +1,48 @@
+#! /bin/sh
+
 name=readline
-version=8.2.10
-revision=1
-tarball_url="https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz"
-tarball_blake2b="7974322b9c092a756a79e537df08e8532f8e0fcb598f77732e28287c33ebec9e9837ed88b43334c310892d56a871b423903f0f564def2fbe700a1004f2ae7b18"
-source_allow_network="yes"
-source_imagedeps="curl"
-source_hostdeps="automake autoconf libtool pkg-config"
-hostdeps="gcc autoconf automake libtool pkg-config"
+_version=8.3
+_patch=1
+version=${_version}.${_patch}
+revision=2
+tarball_url="https://ftpmirror.gnu.org/gnu/readline/readline-${_version}.tar.gz"
+tarball_blake2b="45d6fe7e34c56d309102a94aa776a7f5284201e844450e14ff818df9fa84a72154bdca70f11828c94954b080cbbe4666fa0b00ffa8460118ec8f3ea551b73dad"
+hostdeps="gcc pkg-config"
 deps="core-libs ncurses"
 
-regenerate() {
-    curl -Lo readline82-001 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-001
-    curl -Lo readline82-002 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-002
-    curl -Lo readline82-003 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-003
-    curl -Lo readline82-004 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-004
-    curl -Lo readline82-005 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-005
-    curl -Lo readline82-006 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-006
-    curl -Lo readline82-007 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-007
-    curl -Lo readline82-008 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-008
-    curl -Lo readline82-009 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-009
-    curl -Lo readline82-010 https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-010
+_get_patch() {
+    TMP_PATCH=$(mktemp)
+    curl -Lo "${TMP_PATCH}" https://ftpmirror.gnu.org/gnu/readline/readline-${_version}-patches/readline$(echo "${_version}" | sed 's/\.//g')-$1
+    if ! b2sum "${TMP_PATCH}" | grep -q $2; then
+        die "b2sum checksum fail for readline patch $1
+        expected $2
+        got      $(b2sum "${TMP_PATCH}")"
+    fi
+    patch -p0 <"${TMP_PATCH}"
+}
 
-    for f in readline82-0*; do
-        patch -p0 < $f
-    done
+early_prepare() {
+    _get_patch 001 b0953458a18b8b06b0086567abd3c9ca3efceb5e4c38271e62137e126c106b938945d956394de0e955ecea5d48f8b261a4f2f3db2ee1d2cbc3b4cfdcf213ca46
+}
 
-        AUTOHEADER=true \
+prepare() {
     autotools_recursive_regen
 }
 
-build() {
+configure() {
     autotools_configure \
         --enable-multibyte \
-        --with-curses \
-        CFLAGS="-fPIC -g3 -O0"
+        --with-curses
+}
 
+build() {
     make SHLIB_LIBS="-lncursesw -ltinfow" -j${parallelism}
 }
 
 package() {
     make install DESTDIR="${dest_dir}"
 
-    ln -s libreadline.so.8.2 "${dest_dir}${prefix}"/lib/libreadline.so.8
-    ln -s libhistory.so.8.2 "${dest_dir}${prefix}"/lib/libhistory.so.8
+    install -Dm644 "${base_dir}"/build-support/readline/inputrc "${dest_dir}"/etc/inputrc
 
     post_package_strip
 }
